# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keywords.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="keywords.proto",
    package="keywords",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0ekeywords.proto\x12\x08keywords"\x1f\n\x0eGetKeywordsReq\x12\r\n\x05title\x18\x01 \x01(\t"3\n\x0fGetKeywordsResp\x12 \n\x08keywords\x18\x01 \x03(\x0b\x32\x0e.keywords.Item"$\n\x04Item\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x32O\n\x07Greeter\x12\x44\n\x0bGetKeywords\x12\x18.keywords.GetKeywordsReq\x1a\x19.keywords.GetKeywordsResp"\x00\x62\x06proto3',
)


_GETKEYWORDSREQ = _descriptor.Descriptor(
    name="GetKeywordsReq",
    full_name="keywords.GetKeywordsReq",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="title",
            full_name="keywords.GetKeywordsReq.title",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=59,
)


_GETKEYWORDSRESP = _descriptor.Descriptor(
    name="GetKeywordsResp",
    full_name="keywords.GetKeywordsResp",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="keywords",
            full_name="keywords.GetKeywordsResp.keywords",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=61,
    serialized_end=112,
)


_ITEM = _descriptor.Descriptor(
    name="Item",
    full_name="keywords.Item",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="word",
            full_name="keywords.Item.word",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="weight",
            full_name="keywords.Item.weight",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=114,
    serialized_end=150,
)

_GETKEYWORDSRESP.fields_by_name["keywords"].message_type = _ITEM
DESCRIPTOR.message_types_by_name["GetKeywordsReq"] = _GETKEYWORDSREQ
DESCRIPTOR.message_types_by_name["GetKeywordsResp"] = _GETKEYWORDSRESP
DESCRIPTOR.message_types_by_name["Item"] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetKeywordsReq = _reflection.GeneratedProtocolMessageType(
    "GetKeywordsReq",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETKEYWORDSREQ,
        "__module__": "keywords_pb2"
        # @@protoc_insertion_point(class_scope:keywords.GetKeywordsReq)
    },
)
_sym_db.RegisterMessage(GetKeywordsReq)

GetKeywordsResp = _reflection.GeneratedProtocolMessageType(
    "GetKeywordsResp",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETKEYWORDSRESP,
        "__module__": "keywords_pb2"
        # @@protoc_insertion_point(class_scope:keywords.GetKeywordsResp)
    },
)
_sym_db.RegisterMessage(GetKeywordsResp)

Item = _reflection.GeneratedProtocolMessageType(
    "Item",
    (_message.Message,),
    {
        "DESCRIPTOR": _ITEM,
        "__module__": "keywords_pb2"
        # @@protoc_insertion_point(class_scope:keywords.Item)
    },
)
_sym_db.RegisterMessage(Item)


_GREETER = _descriptor.ServiceDescriptor(
    name="Greeter",
    full_name="keywords.Greeter",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=152,
    serialized_end=231,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetKeywords",
            full_name="keywords.Greeter.GetKeywords",
            index=0,
            containing_service=None,
            input_type=_GETKEYWORDSREQ,
            output_type=_GETKEYWORDSRESP,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name["Greeter"] = _GREETER

# @@protoc_insertion_point(module_scope)
