name: Node Test

defaults:
  run:
    working-directory: frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd frontend lint
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd frontend install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd frontend build # will run `yarn build` command
